### ISSUE TITLE
Devops步骤缺少push镜像的过程

### ISSUE THREAD

**Issue by Xdydy** [faasit/faasit-devops#1]
除了`ft build`以及`ft deploy`，中间应该还要有一个`docker push`的过程，推送到本地的5000端口

```bash
docker tag xxx localhost:5000/library/xxx
docker push localhost:5000/library/xxx
```

**Comment by wushenghao666** [comment]
Fixed in commit: https://github.com/faasit/faasit-devops/commit/11b7913250107d1d7b499b5db0f30bf83a7dc89d
